version: "3.8"

services:

    api:
        container_name: api-container
        build: ./flask_api
        restart: always
        
        command: uwsgi --ini app.ini

        volumes: 
            - api_data:/docker_api
            #把uwsgi log 拿出來
            - ./uwsgi_log:/uwsgi_log

    nginx:
        container_name: nginx-container
        build: ./nginx
        restart: always

        ports: 
            - "80:80"
              
        volumes: 
            - api_data:/docker_api
            #把nginx log 拿出來  
            - ./nginx_log:/var/log/nginx
        depends_on: 
            - api

volumes:
    api_data: 